apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
spec:
  template:
    spec:
      containers:
      - name: flux
        args:
        - --memcached-service=memcached
        - --ssh-keygen-dir=/var/fluxd/keygen
        - --git-url=ssh://workshopper-0@4armed.rocks@source.developers.google.com:2022/p/securing-gke-0/r/flux
        - --git-branch=master
        - --listen-metrics=:3031